# Generated by Django 4.2.7 on 2023-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_picture_delete_image_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature'), ('city', 'City'), ('cars', 'Cars'), ('animals', 'Animals'), ('Hi-Tech', 'Hi-Tech'), ('sport', 'Sport'), ('cosmos', 'Cosmos'), ('science', 'Science')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
