# Generated by Django 4.2.7 on 2023-12-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_tag_options_remove_tag_name_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
