# Generated by Django 4.2.7 on 2023-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='downloads',
            field=models.IntegerField(verbose_name='Скачали'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
    ]
