# Generated by Django 4.2.7 on 2023-12-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_picture_downloads_alter_picture_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature'), ('city', 'City'), ('cars', 'Cars'), ('animals', 'Animals'), ('Hi-Tech', 'Hi-Tech'), ('sport', 'Sport'), ('cosmos', 'Cosmos'), ('science', 'Science'), ('minimalism', 'Minimalism'), ('new year', 'Новый год')], max_length=30),
        ),
    ]
