# Generated by Django 4.2.7 on 2023-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_picture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
