# Generated by Django 4.2.7 on 2023-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(default='main/avatars/ava1.jpg', upload_to='main/avatars/')),
                ('user_nickname', models.CharField(default='Guest', max_length=100)),
                ('image', models.ImageField(default='main/img/picture1.jpg', upload_to='main/img/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
